/**
 * Build script: renders the React homepage to a static HTML string
 * and writes it to homepage-html.ts for import by the Cloudflare Worker.
 *
 * Run: npx tsx src/homepage/build-homepage.ts
 */
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Homepage } from './components/Homepage';

const __dirname = dirname(fileURLToPath(import.meta.url));

const html = '<!DOCTYPE html>' + renderToStaticMarkup(createElement(Homepage));

const output = `// AUTO-GENERATED by build-homepage.ts — do not edit manually
// Regenerate with: npm run build:homepage
export const HOMEPAGE_HTML_TEMPLATE = ${JSON.stringify(html)};
`;

const outPath = resolve(__dirname, 'homepage-html.ts');
writeFileSync(outPath, output, 'utf-8');

console.log(`Homepage HTML written to ${outPath} (${html.length} bytes)`);
