/**
 * Build script: renders the React homepage to a static HTML string
 * and writes it to homepage-html.ts for import by the Cloudflare Worker.
 *
 * Run: npx tsx src/homepage/build-homepage.ts
 */
import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Homepage } from './components/Homepage';

export interface BuildHomepageOptions {
  /**
   * Optional override for the output path. Defaults to
   * `${__dirname}/homepage-html.ts`.
   */
  outPath?: string;
  /**
   * Optional logger function. Defaults to `console.log`.
   */
  log?: (message: string) => void;
  /**
   * Optional file writer. Defaults to `writeFileSync`.
   */
  writeFile?: typeof writeFileSync;
}

/**
 * Builds the static homepage HTML and writes it to the output file.
 * The core logic is encapsulated here to allow unit tests to invoke
 * the build without relying on process-level side effects.
 */
export function buildHomepage(options: BuildHomepageOptions = {}) {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const { outPath: customOutPath, log = console.log, writeFile = writeFileSync } = options;

  const html = '<!DOCTYPE html>' + renderToStaticMarkup(createElement(Homepage));

  const output = `// AUTO-GENERATED by build-homepage.ts — do not edit manually
// Regenerate with: npm run build:homepage
export const HOMEPAGE_HTML_TEMPLATE = ${JSON.stringify(html)};
`;

  const outPath = customOutPath ?? resolve(__dirname, 'homepage-html.ts');
  writeFile(outPath, output, 'utf-8');

  log(`Homepage HTML written to ${outPath} (${html.length} bytes)`);

  return { html, outPath, output };
}

// Only execute the build when run directly under Node.js (e.g. via `npx tsx ...`),
// so that accidental imports from Worker runtime code do not trigger Node APIs.
if (typeof process !== 'undefined' && process.release?.name === 'node') {
  const invokedAsScript =
    typeof process.argv[1] === 'string' &&
    new URL(`file://${process.argv[1]}`).href === import.meta.url;

  if (invokedAsScript) {
    buildHomepage();
  }
}
